# Generated by Django 4.2.9 on 2024-02-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblogapp", "0002_post_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "My Post", "verbose_name_plural": "My Posts"},
        ),
    ]
